name: Roastery policy

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  dependency-review:
    name: Roastery dependency review
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Review pull request dependencies
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        with:
          comment-summary-in-pr: never
      - name: Review merge group dependencies
        if: github.event_name == 'merge_group'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        with:
          base-ref: ${{ github.event.merge_group.base_sha }}
          head-ref: ${{ github.event.merge_group.head_sha }}
          comment-summary-in-pr: never
